# Nombre de la aplicación
spring.application.name=raicespoblanas
server.port=8080

# Configuración de la Base de Datos (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/db_raices_poblanas
spring.datasource.username=postgres
spring.datasource.password=123456789
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuración para subida de imágenes (BYTEA)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Documentación Swagger / OpenAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# GraphQL (Para la navegación OOHDM)
spring.graphql.graphiql.enabled=true

# Límite de carga para imágenes (BYTEA)
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB




