# Nombre de la aplicación
spring.application.name=raicespoblanas

# Configuración de la Base de Datos (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/db_raices_poblanas
spring.datasource.username=postgres
spring.datasource.password=123456789
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Documentación Swagger / OpenAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# GraphQL (Para la navegación OOHDM)
spring.graphql.graphiql.enabled=true

# Límite de carga para imágenes (BYTEA)
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB




